### DOCKER_VERSIONS ############################################################



# Docker image versions

DOCKER_VERSIONS		?= 3.1 3.2 3.3 3.4 3.5 3.6 3.7 edge



### MK_DOCKER_IMAGE ############################################################



PROJECT_DIR		?= $(abspath ../..)
SCRIPT_DIR		:= scripts
MK_DIR			:= mk

include $(PROJECT_DIR)/$(SCRIPT_DIR)/$(MK_DIR)/x.variant.mk



################################################################################