### DOCKER_VERSIONS ############################################################



# Docker image versions

DOCKER_VERSIONS		?= 5 5.1 6



### MK_DOCKER_IMAGE ############################################################



PROJECT_DIR		?= $(abspath ../..)

include $(PROJECT_DIR)/x.variant.mk



################################################################################