### DOCKER_VERSIONS ############################################################



# Docker image versions

DOCKER_VERSIONS		?= 25 26 26-modular 27 rawhide



### MK_DOCKER_IMAGE ############################################################



PROJECT_DIR		?= $(abspath ../..)

include $(PROJECT_DIR)/x.variant.mk



################################################################################