### DOCKER_VERSIONS ############################################################



# Docker image versions

DOCKER_VERSIONS		?= buster buster-slim jessie jessie-slim stretch stretch-slim wheezy wheezy-slim



### MK_DOCKER_IMAGE ############################################################



PROJECT_DIR		?= $(abspath ../..)

include $(PROJECT_DIR)/x.variant.mk



################################################################################