### DOCKER_VERSIONS ############################################################



# Docker image versions

DOCKER_VERSIONS		?= 1-glibc 1.28-glibc 1.28.0-glibc



### MK_DOCKER_IMAGE ############################################################



PROJECT_DIR		?= $(abspath ../..)

include $(PROJECT_DIR)/x.variant.mk



################################################################################