### DOCKER_VERSIONS ############################################################



# Docker image versions

DOCKER_VERSIONS		?= 13.2 14.1 14.2 14.3 leap tumbleweed



### MK_DOCKER_IMAGE ############################################################



PROJECT_DIR		?= $(abspath ../..)

include $(PROJECT_DIR)/x.variant.mk



################################################################################