### DOCKER_VERSIONS ############################################################



# Docker image versions

DOCKER_VERSIONS		?= artful bionic precise trusty xenial yakkety zesty



### MK_DOCKER_IMAGE ############################################################



PROJECT_DIR		?= $(abspath ../..)

include $(PROJECT_DIR)/x.variant.mk



################################################################################